FROM ghcr.io/pantheontech/stonework:latest

WORKDIR /root

SHELL ["/bin/bash", "-c"]

CMD ["INITIAL_LOGLVL=debug MICROSERVICE_LABEL=stonework ETCD_CONFIG= CNF_MGMT_SUBNET=127.0.0.1/8 ./stonework-gns3-startup.sh"]
