FROM stonework:latest

WORKDIR /root

SHELL ["/bin/bash", "-c"]

ENV INITIAL_LOGLVL debug

ENV MICROSERVICE_LABEL stonework

ENV ETCD_CONFIG

ENV CNF_MGMT_SUBNET 127.0.0.1/8

CMD ["/root/stonework-gns3-startup.sh"]
